version: "3"
services:
    db:
        build: ./mysql/
        container_name: drive_inventory_db
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_DATABASE: drive_inventory_db
            MYSQL_ROOT_PASSWORD: root
    app:
        build: ./
        container_name: myapp
        links:
            - "db"
        ports:
            - "5001:5000"
